[package]
name = "day25-part1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrixcompare = "0.3.0"
nalgebra = "0.32.3"
nalgebra-sparse = "0.9.0"
sprs = "0.11.1"
svdlibrs = "0.5.1"
